import numpy as np
import scipy.io as sio
import time


def export_hrir_to_matfile(filename_s, hl, hr, comments_custom=''):
    """

    :param filename_s:      filename for the output mat-file
    :param hl:              HrtfData class for left ear
    :param hr:              HrtfData class for right ear
    :param comments_custom: user comments
    :return: 0 if save ok
    """
    # CHECK
    assert hl.fs_f == hr.fs_f, 'Left and right sampling frequency must be the same'
    assert np.all(hl.azim_v == hr.azim_v), 'Left and right azim list must be the same'
    assert np.all(hl.elev_v == hr.elev_v), 'Left and right elev list must be the same'
    assert np.all(hl.dist_v == hr.dist_v), 'Left and right elev list must be the same'

    # BUILD VARIABLES
    fs = hl.fs_f
    comments = 'HRIR file generated by Python binauralbox on' + time.asctime() + '\n' + comments_custom
    coords = np.concatenate((hl.dist_v[:, np.newaxis],
                             hl.azim_v[:, np.newaxis],
                             hl.elev_v[:, np.newaxis]),
                            axis=1)
    hl_data = hl.data_m
    hr_data = hr.data_m

    # SAVE MAT-FILE
    sio.savemat(filename_s,
                {'comments': comments, 'coords': coords, 'Fs': fs, 'hl': hl_data, 'hr': hr_data, 'vers': '1.1'})
    print('SAVE HRIR MAT-FILE: ' + filename_s)
    return 0

